/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Login;

import Admin.AdminAndUserModule;
import Admin.Dashboard;
import Admin.Service;
import Users.Main.Correct;
import Users.Main.Main;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.io.*;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
public class CreateAccount extends javax.swing.JFrame {

    AdminAndUserModule admin;
    ArrayList<AdminAndUserModule> arrayAdmin;
    String where = "";
    public CreateAccount() {
        initComponents();
        this.setFocusable(rootPaneCheckingEnabled);
          this.setTitle("Knowledge");
        arrayAdmin=new ArrayList<>();
         fillArrayList();
        lbl_generate1.hide();
    }
     int display = 0;
     Timer timer = new Timer(1000, new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent e){
           display++;
              if(display == 2){
                          
                            if(where.equals("user")){
                            new Main().setVisible(true);
                            }else if(where.equals("admin")){
                                new Dashboard().setVisible(true);
                            }  
                              timer.stop();
                   }
        }      
    });
    
      public void SavingandRetrieving(){
              try{    
                    FileOutputStream outFile = new FileOutputStream("AdminAndUser.ser");
                            ObjectOutputStream outObj =   new ObjectOutputStream(outFile);
                             outObj.writeObject(arrayAdmin);                 
                      System.out.println(" Saved");
                       outObj.close();
                }catch(IOException e) {
                    System.out.println(e);
                }
              
      }
  
        public void fillArrayList()  {
         try{
                   FileInputStream fileInputStream=new FileInputStream(new File("AdminAndUser.ser"));
                    ObjectInputStream stream=new ObjectInputStream(fileInputStream);
                    for(Object objectAdmin : (ArrayList)stream.readObject())
                    {
                       AdminAndUserModule module = (AdminAndUserModule) objectAdmin;
                        arrayAdmin.add(module);
                    }

            }catch(IOException e){
                System.out.println("FileNotFound");   
            } catch (ClassNotFoundException ex) {
                System.out.println(ex);
        }
    }
        public boolean isUsernameExist(String username){
            boolean isExist = false;
                for(int i = 0; i < arrayAdmin.size() ; i++){
                               if(arrayAdmin.get(i).getUsername().equals(username)){
                                   isExist = true;
                                   break;
                               }
                           }
                return isExist;
     }
          public String   QuizIdGenerator(String whereTo ){
         String id = "";
         Date now = new Date();
         int year = now.getYear();
         int date = now.getDate();
         int month = now.getMonth()+ 1;
             if(arrayAdmin.isEmpty()){
                id = whereTo + (year + 1900) + "-"+ month + "/"+date+ "-" + "1101";
        }else{
             int lastQuizIdIndex =  arrayAdmin.size() - 1;
            String adminValueID =  arrayAdmin.get(lastQuizIdIndex).getId();
            String [] arrayLastId = adminValueID.split("-", -1);
            id =    whereTo + (year + 1900) + "-"+ month+ "/"+date+ "-" + (Integer.parseInt(arrayLastId[2]) + 1);
        }
           
         return id;
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_generate = new javax.swing.JLabel();
        lbl_generate1 = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        lbl_firstname = new javax.swing.JLabel();
        lbl_lastname = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_firstname = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        txt_lastname = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_exit = new javax.swing.JLabel();
        btn_create = new javax.swing.JButton();
        ck_user = new javax.swing.JCheckBox();
        ck_admin = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_generate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_generate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/generate35.png"))); // NOI18N
        lbl_generate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_generateMouseEntered(evt);
            }
        });
        jPanel1.add(lbl_generate, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 300, 40, 40));

        lbl_generate1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_generate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-stumbleupon-35.png"))); // NOI18N
        lbl_generate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_generate1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_generate1MouseExited(evt);
            }
        });
        jPanel1.add(lbl_generate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 300, 40, 40));

        lbl_password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_password.setText("Password");
        jPanel1.add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 90, 40));

        lbl_username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_username.setText("Username");
        jPanel1.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 90, 40));

        lbl_firstname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_firstname.setText("Firstname");
        jPanel1.add(lbl_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 90, 40));

        lbl_lastname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_lastname.setText("Lastname");
        jPanel1.add(lbl_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 90, 40));

        txt_username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_username.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 370, 40));

        txt_firstname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_firstname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_firstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_firstnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_firstnameFocusLost(evt);
            }
        });
        jPanel1.add(txt_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 370, 40));

        txt_password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_password.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_passwordFocusLost(evt);
            }
        });
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 320, 40));

        txt_lastname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_lastname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_lastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_lastnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_lastnameFocusLost(evt);
            }
        });
        jPanel1.add(txt_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 370, 40));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 410, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 410, 20));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 410, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 410, 20));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/name-25 .png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 40, 40));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-name-30.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 40, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/username.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 40, 40));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-keepass-30.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 40, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emoji4.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 230, 260));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/createAccount.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 550, 80));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 160, 120));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emoji3.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 360, 290));

        lbl_exit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_exit.setForeground(new java.awt.Color(255, 0, 51));
        lbl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit.setText("X");
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_exitMouseExited(evt);
            }
        });
        jPanel1.add(lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 30, 40));

        btn_create.setBackground(new java.awt.Color(0, 204, 255));
        btn_create.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        btn_create.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emoji5.png"))); // NOI18N
        btn_create.setText("Create");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });
        jPanel1.add(btn_create, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 210, 60));

        ck_user.setBackground(new java.awt.Color(255, 255, 255));
        ck_user.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        ck_user.setText("User");
        ck_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ck_userMouseClicked(evt);
            }
        });
        ck_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_userActionPerformed(evt);
            }
        });
        jPanel1.add(ck_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, -1, -1));

        ck_admin.setBackground(new java.awt.Color(255, 255, 255));
        ck_admin.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        ck_admin.setText("Admin");
        ck_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_adminActionPerformed(evt);
            }
        });
        jPanel1.add(ck_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, -1, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/MainLogo.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 420, 140));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_generateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_generateMouseEntered
        lbl_generate.hide();
        lbl_generate1.show();
    }//GEN-LAST:event_lbl_generateMouseEntered

    private void lbl_generate1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_generate1MouseClicked
        String generatedPass = new Service().autoGeneratedPassword();
        lbl_password.hide();
        txt_password.setText(generatedPass);
    }//GEN-LAST:event_lbl_generate1MouseClicked

    private void lbl_generate1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_generate1MouseExited
        lbl_generate1.hide();
        lbl_generate.show();
    }//GEN-LAST:event_lbl_generate1MouseExited

    private void txt_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusGained
        lbl_username.hide();
    }//GEN-LAST:event_txt_usernameFocusGained

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost
        if(txt_username.getText().trim().equals("")){
            lbl_username.show();
        }
    }//GEN-LAST:event_txt_usernameFocusLost

    private void txt_firstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_firstnameFocusGained
        lbl_firstname.hide();
    }//GEN-LAST:event_txt_firstnameFocusGained

    private void txt_firstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_firstnameFocusLost
        if(  txt_firstname.getText().trim().equals("")){
            lbl_firstname.show();
        }
    }//GEN-LAST:event_txt_firstnameFocusLost

    private void txt_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusGained

        lbl_password.hide();
    }//GEN-LAST:event_txt_passwordFocusGained

    private void txt_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusLost
        if( txt_password.getText().trim().equals("")){
            lbl_password.show();
        }
    }//GEN-LAST:event_txt_passwordFocusLost

    private void txt_lastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_lastnameFocusGained
        lbl_lastname.hide();
    }//GEN-LAST:event_txt_lastnameFocusGained

    private void txt_lastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_lastnameFocusLost
        if(  txt_lastname.getText().trim().equals("")){
            lbl_lastname.show();
        }
    }//GEN-LAST:event_txt_lastnameFocusLost

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        this.dispose();
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void lbl_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseEntered

    }//GEN-LAST:event_lbl_exitMouseEntered

    private void lbl_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseExited

    }//GEN-LAST:event_lbl_exitMouseExited
 int xx , xy ;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
            xx = evt.getX();
     xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
      int y = evt.getYOnScreen();
      this.setLocation(x -xx , y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void ck_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ck_userMouseClicked
            
    }//GEN-LAST:event_ck_userMouseClicked

    private void ck_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_userActionPerformed
            if(ck_user.isSelected()){
                ck_admin.setSelected(false);
                  where = "user";
               
            }
    }//GEN-LAST:event_ck_userActionPerformed

    private void ck_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_adminActionPerformed
         if(ck_admin.isSelected()){
                ck_user.setSelected(false);
                where = "admin";
            }
    }//GEN-LAST:event_ck_adminActionPerformed

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
            
        if(!ck_admin.isSelected() && !ck_user.isSelected()){
                JOptionPane.showMessageDialog(null , "Please Select if you are a User or Admin", "Create Validator", JOptionPane.WARNING_MESSAGE);
                return;
        }
                        String username  = txt_username.getText();
                        String password = txt_password.getText();
                        String firstname  = txt_firstname.getText();
                        String lastname = txt_lastname.getText();
                        String ID = QuizIdGenerator(where);
                        
                if(username.isEmpty() || password.isEmpty() || firstname.isEmpty() || lastname.isEmpty() ){ 
                        JOptionPane.showMessageDialog(null, "Complete All the Details", "Saving Validator", WIDTH, null);
                        return;
                }
              
                if(isUsernameExist(username)){
                    JOptionPane.showMessageDialog(null, "Username Already Taken", "Saving Validator", WIDTH, null);
                        return;
                }
                try{
                        admin = new AdminAndUserModule(ID,username,new Service().md5_Password(password),firstname,lastname, where);
                        arrayAdmin.add(admin);
                        timer.start();
                        SavingandRetrieving();
                        new Service().loginUsername = username;
                         new Service().loginAdminOrUserID =  ID;
                         Correct  correct = new Correct();
                         correct.pack();
                          correct.lbl_exit.setVisible(false);
                           correct.jLabel2.setText("Successfully Created");
                           correct.setVisible(true);
                                    
                        this.dispose();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "e", "Saving Validator", WIDTH, null);
                }
    }//GEN-LAST:event_btn_createActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       this.dispose();
       new LoginForm().setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_create;
    private javax.swing.JCheckBox ck_admin;
    private javax.swing.JCheckBox ck_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_firstname;
    private javax.swing.JLabel lbl_generate;
    private javax.swing.JLabel lbl_generate1;
    private javax.swing.JLabel lbl_lastname;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
