/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Admin;
import Admin.CreatingQuiz.Easy.Easy;
import Admin.showingQuiz.ShowEasy;
import Login.LoginForm;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Jason
 */
public class Admin extends javax.swing.JFrame {

  AdminAndUserModule admin;
    ArrayList<AdminAndUserModule> arrayAdmin;
    
    public Admin() {
    
        this.setTitle("Knowledge");
         arrayAdmin=new ArrayList<>();
        initComponents();
        this.setFocusable(rootPaneCheckingEnabled);
        showDate();
        showTime();
         fillArrayList();
         displayList();
         btn_search1.hide();
     
      
    }
  
 void showDate()
        {
            Date d= new Date();
            SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
            lbl_date.setText(s.format(d));
        }
        void showTime()
        {
           new Timer(0, new ActionListener(){

                @Override
                public void actionPerformed(ActionEvent e) {
                     Date d= new Date();
             SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
             lbl_time.setText(s.format(d));
                }

            
            }).start();
        }
        
          public void SavingandRetrieving(){
              try{    
                    FileOutputStream outFile = new FileOutputStream(new File("AdminAndUser.ser"));
                            ObjectOutputStream outObj =   new ObjectOutputStream(outFile);
                             outObj.writeObject(arrayAdmin);                                           
                       outObj.close();
                }catch(IOException e) {
                    System.out.println(e);
                }
              
      }
  
        public void fillArrayList()  {
         try{
                   FileInputStream fileInputStream=new FileInputStream(new File("AdminAndUser.ser"));
                    ObjectInputStream stream=new ObjectInputStream(fileInputStream);
                    for(Object objectAdmin : (ArrayList)stream.readObject())
                    {
                       AdminAndUserModule module = (AdminAndUserModule) objectAdmin;
                        arrayAdmin.add(module);
                    }
               fileInputStream.close();
                    stream.close();
            }catch(IOException e){
                System.out.println("FileNotFound");   
            } catch (ClassNotFoundException ex) {
                System.out.println(ex);
        }
    }
          public void displayList(){
          arrayAdmin.clear();
           fillArrayList();
           DefaultTableModel model = (DefaultTableModel) tbl_admin.getModel();
            for(AdminAndUserModule admin: arrayAdmin){
                    if(admin.getUser().equals("admin")){
                        if(!admin.getId().equals(new Service().loginAdminOrUserID)){
                               model.addRow(new Object[]{admin.getUsername(), admin.getFirstname(), admin.getLastname()});
                        }
                         
                    }
           
            }
        
    }
      public void TableRemoveElement(){
            DefaultTableModel model = (DefaultTableModel)tbl_admin.getModel();
             model.getDataVector().removeAllElements();
                model.fireTableDataChanged();
      }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpl_dashboard = new javax.swing.JPanel();
        lbl_dashboard = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        ProfileIcon = new javax.swing.JLabel();
        jpl_admin = new javax.swing.JPanel();
        lbl_admin = new javax.swing.JLabel();
        jpl_users = new javax.swing.JPanel();
        lbl_users = new javax.swing.JLabel();
        jpl_showingQuiz = new javax.swing.JPanel();
        lbl_showQuiz = new javax.swing.JLabel();
        jpl_creatingQuiz = new javax.swing.JPanel();
        lbl_creatingQuiz = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_admin = new javax.swing.JTable();
        btn_create = new javax.swing.JButton();
        btn_view = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_reload = new javax.swing.JButton();
        btn_search = new javax.swing.JLabel();
        btn_search1 = new javax.swing.JLabel();
        lbl_search = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpl_dashboard.setBackground(new java.awt.Color(245, 245, 245));
        jpl_dashboard.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpl_dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_dashboard.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_dashboard.setForeground(new java.awt.Color(153, 153, 153));
        lbl_dashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/LeaderBoardGILID.png"))); // NOI18N
        lbl_dashboard.setText("Leaderboard");
        lbl_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_dashboardMouseExited(evt);
            }
        });
        jpl_dashboard.add(lbl_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 110));

        jPanel1.add(jpl_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 360, 110));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png"))); // NOI18N
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 150, 140));

        jLabel3.setFont(new java.awt.Font("Bell MT", 3, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 204, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ACLC COLLEGE ");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 250, -1));
        jPanel7.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 210, 10));
        jPanel7.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 210, 10));

        jLabel2.setFont(new java.awt.Font("Bell MT", 3, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Taclocban Inc.");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 200, 30));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 170));

        ProfileIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        ProfileIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileIconMouseClicked(evt);
            }
        });
        jPanel1.add(ProfileIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 50, 60, 90));

        jpl_admin.setBackground(new java.awt.Color(204, 204, 204));
        jpl_admin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpl_admin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_admin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_admin.setForeground(new java.awt.Color(51, 204, 255));
        lbl_admin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/admin.png"))); // NOI18N
        lbl_admin.setText("Admin");
        lbl_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_adminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_adminMouseExited(evt);
            }
        });
        jpl_admin.add(lbl_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 110));

        jPanel1.add(jpl_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 360, 110));

        jpl_users.setBackground(new java.awt.Color(245, 245, 245));
        jpl_users.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpl_users.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_users.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_users.setForeground(new java.awt.Color(153, 153, 153));
        lbl_users.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/multipleUser.png"))); // NOI18N
        lbl_users.setText("Users      ");
        lbl_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_usersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_usersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_usersMouseExited(evt);
            }
        });
        jpl_users.add(lbl_users, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 110));

        jPanel1.add(jpl_users, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 360, 110));

        jpl_showingQuiz.setBackground(new java.awt.Color(245, 245, 245));
        jpl_showingQuiz.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpl_showingQuiz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_showQuiz.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_showQuiz.setForeground(new java.awt.Color(153, 153, 153));
        lbl_showQuiz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_showQuiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/showQuiz.png"))); // NOI18N
        lbl_showQuiz.setText("Show Quiz");
        lbl_showQuiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_showQuizMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_showQuizMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_showQuizMouseExited(evt);
            }
        });
        jpl_showingQuiz.add(lbl_showQuiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 340, 110));

        jPanel1.add(jpl_showingQuiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 360, 110));

        jpl_creatingQuiz.setBackground(new java.awt.Color(245, 245, 245));
        jpl_creatingQuiz.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpl_creatingQuiz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_creatingQuiz.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_creatingQuiz.setForeground(new java.awt.Color(153, 153, 153));
        lbl_creatingQuiz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_creatingQuiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/createQuiz.png"))); // NOI18N
        lbl_creatingQuiz.setText("Create Quiz");
        lbl_creatingQuiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_creatingQuizMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_creatingQuizMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_creatingQuizMouseExited(evt);
            }
        });
        jpl_creatingQuiz.add(lbl_creatingQuiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 110));

        jPanel1.add(jpl_creatingQuiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 360, 110));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 1050, 10));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-time-18.png"))); // NOI18N

        lbl_date.setText("Date");

        lbl_time.setText("Time");

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-polyline-20.png"))); // NOI18N

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-polyline-20.png"))); // NOI18N

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-polyline-20.png"))); // NOI18N

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-polyline-20.png"))); // NOI18N

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-polyline-20.png"))); // NOI18N

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-polyline-20.png"))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Bell MT", 3, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 51, 51));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        jLabel26.setText("Logout");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Male_User_16.png"))); // NOI18N
        jLabel27.setText("Login as: Admin");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_date)
                .addGap(51, 51, 51)
                .addComponent(lbl_time)
                .addGap(95, 95, 95)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_date, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_time, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(73, 73, 73))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 680, 1040, 40));

        jLabel28.setFont(new java.awt.Font("Bell MT", 3, 28)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 204, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/admin.png"))); // NOI18N
        jLabel28.setText("Admin Dashboard");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 330, 90));
        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 60, -1, -1));

        tbl_admin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl_admin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Firstname", "Lastname"
            }
        ));
        tbl_admin.setRowHeight(40);
        jScrollPane2.setViewportView(tbl_admin);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 261, 1000, 410));

        btn_create.setBackground(new java.awt.Color(0, 255, 0));
        btn_create.setFont(new java.awt.Font("Bell MT", 1, 15)); // NOI18N
        btn_create.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add-22.png"))); // NOI18N
        btn_create.setText("Create New");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });
        jPanel1.add(btn_create, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 150, 50));

        btn_view.setBackground(new java.awt.Color(255, 255, 102));
        btn_view.setFont(new java.awt.Font("Bell MT", 1, 15)); // NOI18N
        btn_view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-view-25.png"))); // NOI18N
        btn_view.setText("View");
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });
        jPanel1.add(btn_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 160, 50));

        btn_delete.setBackground(new java.awt.Color(255, 51, 51));
        btn_delete.setFont(new java.awt.Font("Bell MT", 1, 15)); // NOI18N
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-delete-22.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 150, 50));

        btn_reload.setBackground(new java.awt.Color(153, 255, 255));
        btn_reload.setFont(new java.awt.Font("Bell MT", 1, 15)); // NOI18N
        btn_reload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-process-25.png"))); // NOI18N
        btn_reload.setText("Reload");
        btn_reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reloadActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reload, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, 180, 50));

        btn_search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-search-25.png"))); // NOI18N
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_searchMouseExited(evt);
            }
        });
        jPanel1.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 170, 40, 40));

        btn_search1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_search1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-search-25 (1).png"))); // NOI18N
        btn_search1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_search1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_search1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_search1MouseExited(evt);
            }
        });
        jPanel1.add(btn_search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 170, 40, 40));

        lbl_search.setText("SEARCH USERNAME:");
        jPanel1.add(lbl_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 190, 130, -1));

        txt_search.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_searchFocusLost(evt);
            }
        });
        jPanel1.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 180, 230, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 210, 260, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 1050, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 0, 50, 50));

        jLabel29.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 204, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Stay Safe & Healthy");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 220, 30));

        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("Your information will not displayed on the table*  click the profile icon to show your info");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 236, 510, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
       int p = JOptionPane.showConfirmDialog(null, "Are u sure u want to exit", "Logout Exit",JOptionPane.YES_NO_OPTION);
        if(p == 0){
         
           this.dispose();
            new LoginForm().setVisible(true);
        }
    }//GEN-LAST:event_jLabel26MouseClicked

    private void lbl_creatingQuizMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_creatingQuizMouseEntered
       setColor(jpl_creatingQuiz, lbl_creatingQuiz);
       resetColor(jpl_admin, lbl_admin);
    }//GEN-LAST:event_lbl_creatingQuizMouseEntered

    private void lbl_creatingQuizMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_creatingQuizMouseExited
       resetColor(jpl_creatingQuiz, lbl_creatingQuiz);
       setColor(jpl_admin, lbl_admin);
    }//GEN-LAST:event_lbl_creatingQuizMouseExited

    private void lbl_showQuizMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_showQuizMouseEntered
       setColor(jpl_showingQuiz, lbl_showQuiz);
       resetColor(jpl_admin, lbl_admin);
    }//GEN-LAST:event_lbl_showQuizMouseEntered

    private void lbl_showQuizMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_showQuizMouseExited
      resetColor(jpl_showingQuiz, lbl_showQuiz);
       setColor(jpl_admin, lbl_admin);
    }//GEN-LAST:event_lbl_showQuizMouseExited

    private void lbl_usersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_usersMouseEntered
        setColor( jpl_users,  lbl_users);
       resetColor(jpl_admin, lbl_admin);
    }//GEN-LAST:event_lbl_usersMouseEntered

    private void lbl_usersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_usersMouseExited
        resetColor(jpl_users,  lbl_users);
       setColor(jpl_admin, lbl_admin);
    }//GEN-LAST:event_lbl_usersMouseExited

    private void lbl_adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_adminMouseEntered
      
    }//GEN-LAST:event_lbl_adminMouseEntered

    private void lbl_adminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_adminMouseExited
   
    }//GEN-LAST:event_lbl_adminMouseExited

    private void lbl_creatingQuizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_creatingQuizMouseClicked
        this.dispose();
        
            new Easy().setVisible(true);
       
    }//GEN-LAST:event_lbl_creatingQuizMouseClicked

    private void lbl_showQuizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_showQuizMouseClicked
       this.dispose();
       new ShowEasy().setVisible(true);
    }//GEN-LAST:event_lbl_showQuizMouseClicked
 int xx , xy ;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
         xx = evt.getX();
     xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
         int x = evt.getXOnScreen();
      int y = evt.getYOnScreen();
      this.setLocation(x -xx , y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
       new AddAdmin().setVisible(true);
    }//GEN-LAST:event_btn_createActionPerformed
 View v = new View();
    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
                 if(tbl_admin.getSelectionModel().isSelectionEmpty()){
                JOptionPane.showMessageDialog(null, "SELECT to View" , "View  VALIDATOR", WIDTH, null);
            }else{
                int index  = tbl_admin.getSelectedRow();
                TableModel model = tbl_admin.getModel();
                String username  = model.getValueAt(index, 0).toString();
                new Service().username = username;
                new View().setVisible(true);
        }
    }//GEN-LAST:event_btn_viewActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
             if(tbl_admin.getSelectionModel().isSelectionEmpty()){
                JOptionPane.showMessageDialog(null, "SELECT  TO DELETE" , "DELETE VALIDATOR", WIDTH, null);
            }else{
                int index  = tbl_admin.getSelectedRow();
                TableModel model = tbl_admin.getModel();
                String username  = model.getValueAt(index, 0).toString();
                
                int p = JOptionPane.showConfirmDialog(null, "Are you sure u want to delete this?" , "DELETE QUIZ" , JOptionPane.YES_NO_OPTION);
                
                    if(p == 0){
                           for(int i = 0; i < arrayAdmin.size() ; i++){
                               if(arrayAdmin.get(i).getUsername().contains(username)){
                                    arrayAdmin.remove(i);
                                   JOptionPane.showMessageDialog(null, "Successfully Deleted");
                                 
                               
                                   break;
                               }
                           }
                              SavingandRetrieving();
                              TableRemoveElement();
                              displayList();
                    }
                 
                    
            }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_reloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reloadActionPerformed
            btn_search1.hide();
            btn_search.show();
            txt_search.setText(null);
            lbl_search.show();
            TableRemoveElement();
             displayList();
    }//GEN-LAST:event_btn_reloadActionPerformed

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseClicked

    }//GEN-LAST:event_btn_searchMouseClicked

    private void btn_searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseEntered
        btn_search.hide();
        btn_search1.show();
    }//GEN-LAST:event_btn_searchMouseEntered

    private void btn_searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseExited

    }//GEN-LAST:event_btn_searchMouseExited

    private void btn_search1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search1MouseClicked
        
        if(txt_search.getText().isEmpty()){
         JOptionPane.showMessageDialog(null, "Seach Username Must not be Empty!!", "Search Validator", JOptionPane.WARNING_MESSAGE );
         return;
        }
        TableRemoveElement();
        DefaultTableModel model = (DefaultTableModel) tbl_admin.getModel();
        String searchVal  = txt_search.getText();
         for(AdminAndUserModule admin: arrayAdmin){
                    if(admin.getUsername().contains(searchVal)){
                          if(!admin.getId().equals(new Service().loginAdminOrUserID)){
                         model.addRow(new Object[]{admin.getUsername(), admin.getLastname(), admin.getFirstname()});
                          
                         }
                    }
               
            }
    }//GEN-LAST:event_btn_search1MouseClicked

    private void btn_search1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_search1MouseEntered

    private void btn_search1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search1MouseExited
        btn_search1.hide();
        btn_search.show();
    }//GEN-LAST:event_btn_search1MouseExited

    private void txt_searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_searchFocusGained
        lbl_search.hide();
    }//GEN-LAST:event_txt_searchFocusGained

    private void txt_searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_searchFocusLost
        if(txt_search.getText().trim().equals("")){
            lbl_search.show();
        }
    }//GEN-LAST:event_txt_searchFocusLost

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void lbl_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_dashboardMouseEntered
       setColor( jpl_dashboard,  lbl_dashboard);
       resetColor(jpl_admin, lbl_admin);
    }//GEN-LAST:event_lbl_dashboardMouseEntered

    private void lbl_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_dashboardMouseExited
        resetColor(jpl_dashboard,  lbl_dashboard);
        setColor(jpl_admin, lbl_admin);
    }//GEN-LAST:event_lbl_dashboardMouseExited

    private void lbl_usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_usersMouseClicked
       this.dispose();
       new Users().setVisible(true);
    }//GEN-LAST:event_lbl_usersMouseClicked

    private void lbl_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_dashboardMouseClicked
       this.dispose();
       new Dashboard().setVisible(true);
    }//GEN-LAST:event_lbl_dashboardMouseClicked

    private void ProfileIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileIconMouseClicked

          new ProfileViewer().setVisible(true);
        
    }//GEN-LAST:event_ProfileIconMouseClicked

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ProfileIcon;
    private javax.swing.JButton btn_create;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_reload;
    private javax.swing.JLabel btn_search;
    private javax.swing.JLabel btn_search1;
    private javax.swing.JButton btn_view;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel jpl_admin;
    private javax.swing.JPanel jpl_creatingQuiz;
    private javax.swing.JPanel jpl_dashboard;
    private javax.swing.JPanel jpl_showingQuiz;
    private javax.swing.JPanel jpl_users;
    private javax.swing.JLabel lbl_admin;
    private javax.swing.JLabel lbl_creatingQuiz;
    private javax.swing.JLabel lbl_dashboard;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_search;
    private javax.swing.JLabel lbl_showQuiz;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JLabel lbl_users;
    private javax.swing.JTable tbl_admin;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
    void setColor(JPanel panel, JLabel label) {
       panel.setBackground(new Color(204,204, 204));
       label.setForeground(new Color(51, 204, 255));
    }
       void resetColor(JPanel panel, JLabel label) {
       panel.setBackground(new Color(245,245, 245));
       label.setForeground(new Color(153,153,153));
    }

}
