/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Admin;

import java.security.MessageDigest;
import java.util.Random;

/**
 *
 * @author Jason
 */
public class Service {
    public static String username;
    
    public String  autoGeneratedPassword(){
            int leftLimit = 48; 
    int rightLimit = 122;
    int targetStringLength = 12;
    Random random = new Random();

    String generatedString = random.ints(leftLimit, rightLimit + 1)
      .filter(i -> (i <= 57 || i >= 65) && (i <= 90 || i >= 97))
      .limit(targetStringLength)
      .collect(StringBuilder::new, StringBuilder::appendCodePoint, StringBuilder::append)
      .toString();
    return generatedString;
    }
     public  String md5_Password(final String toEncrypt) {
        try {
            final MessageDigest digest = MessageDigest.getInstance("md5");
            digest.update(toEncrypt.getBytes());
            final byte[] bytes = digest.digest();
            final StringBuilder sb = new StringBuilder();
            for (int i = 0; i < bytes.length; i++) {
                sb.append(String.format("%02X", bytes[i]));
            }
            return sb.toString().toLowerCase();
        } catch (Exception exc) {
            return ""; // Impossibru!
        }
        
    }
    public  String  copy = "Jason P. Cabral";
   
   public static String loginUsername;
   public static String loginAdminOrUserID;
  
}
